name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repo
        uses: actions/checkout@v3
      - name: Seek for joke
        uses: ./.github/actions/joke-action
